<?php echo $this->doctype();?>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <!-- title -->
        <?php echo $this->headTitle($this->translate('File exchange service'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <!-- meta -->
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0, user-scalable=no')

        ?>
        <!-- styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/admin.css'));
        ?>
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/main.js'))
            ->prependFile('https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js');
            
        ?>
        <link href="https://fonts.googleapis.com/css?family=Istok+Web:400,700&amp;subset=latin,cyrillic" rel="stylesheet" type="text/css">
    </head>
<body>
<header>
    <h1 class="tind60">
        <a href="/">
            <?php echo $this->translate(_('Upload file service')); ?>
        </a>
    </h1>
    <div class="lang">
        <a href="/" onclick="return false;" class="flag" style="background-image: url('/img/langs/<?php echo $this->currentLang; ?>.png');"></a>
        <div class="langs">
            <?php foreach ($this->langs as $lang): ?>
                <?php if ($lang[0] != $this->currentLang): ?>
                    <div class="langitem">
                        <a href="<?php echo '/?lang='.$lang[0]; ?>" ><span style="background-image: url('/img/langs/<?php echo $lang[0]; ?>.png')"></span> 
                            <?php echo $this->translate($lang[1]); ?>
                        </a>
                    </div>
                <?php endif; ?>
            <?php endforeach ?>
        </div>
    </div>
    <div class="logout">
        <a href="/user/logout"></a>
    </div>
</header>
<?php echo $this->content; ?>
</body>
</html>